version: "3"

services:
    backend:
        build: ./
        expose: 
            - "5000"
        # environment: 
        #     API_HOST: "http://localhost:3000"
        #     APP_SERVER_PORT: 5000
        ports: 
            - "5000:5000"
        volumes: 
            - .:/app
        command: gunicorn server:app -c ./gunicorn.conf.py
        # command: python server.py

        networks: 
            - app-test
    frontend:
        build: ./frontend
        expose: 
            - "3000"
        ports: 
            - "3000:3000"
        volumes: 
            - ./frontend:/app
        networks: 
            - app-test
        depends_on: 
            - backend
        environment: 
            - NODE_ENV=development
            - HOST_URL="http://backend:5000"
        links:
            - backend
        command: yarn start
        

networks:
    app-test:
        driver: bridge
